services:
  postgres:
    container_name: postgres-rpg-system-backend
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rpg-system-backend
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"

  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm run start"
    container_name: rpg-system-backend-api
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/rpg-system-backend
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  data:
    driver: local
